# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 18:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVICE', '0003_auto_20171028_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a Title', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('activity', models.CharField(help_text='Enter an activity', max_length=200)),
                ('request', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief desciption of the service', max_length=1000)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('request', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook_Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('request', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a tutor service title', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the tutor', max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Enter the of each tutor session', max_digits=6)),
                ('subject', models.TextField(help_text='Enter the subject', max_length=100)),
                ('request', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.CharField(blank=True, choices=[('vb', 'Very Bad'), ('b', 'Bad'), ('g', 'Good'), ('vg', 'Very Good')], default='vb', help_text='Rate Me', max_length=1),
        ),
        migrations.AddField(
            model_name='tutor',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERVICE.Profile'),
        ),
        migrations.AddField(
            model_name='textbook_trading',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERVICE.Profile'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERVICE.Profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERVICE.Profile'),
        ),
    ]
