# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVICE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
