# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVICE', '0002_auto_20171210_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycomment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='carpoolcomment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='textbookcomment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='tutorcomment',
            name='approved_comment',
        ),
    ]
